# Generated by Django 3.0.5 on 2021-03-14 04:05

import ILS.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=50)),
                ('pageCount', models.IntegerField()),
                ('publishedDate', models.DateField()),
                ('thumbnailURL', models.CharField(max_length=200)),
                ('shortDescription', models.CharField(blank=True, max_length=100)),
                ('longDescription', models.CharField(blank=True, max_length=355)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('MEAP', 'MEAP')], max_length=10)),
                ('authors', djongo.models.fields.ArrayField(model_container=ILS.models.Author)),
                ('categories', djongo.models.fields.ArrayField(model_container=ILS.models.Category)),
            ],
        ),
    ]
