# Generated by Django 3.0.5 on 2021-03-14 05:50

import ILS.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ILS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedField(model_container=ILS.models.Blog)),
                ('meta_data', djongo.models.fields.EmbeddedField(model_container=ILS.models.MetaData)),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('authors', djongo.models.fields.ArrayField(model_container=ILS.models.Author, model_form_class=ILS.models.AuthorForm)),
                ('n_comments', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=djongo.models.fields.ArrayField(model_container=ILS.models.Author, model_form_class=ILS.models.AuthorForm),
        ),
    ]
