# Generated by Django 3.0.5 on 2021-03-14 05:55

import ILS.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ILS', '0002_auto_20210314_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.AddField(
            model_name='entry',
            name='tasks',
            field=djongo.models.fields.ArrayField(default=1, model_container=ILS.models.Task, model_form_class=ILS.models.TaskForm),
            preserve_default=False,
        ),
    ]
